#ifndef QTSHERPAONNX_GLOBAL_H
#define QTSHERPAONNX_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(QT6SHERPAONNX_LIBRARY)
#define QT6SHERPAONNX_EXPORT Q_DECL_EXPORT
#else
#define QT6SHERPAONNX_EXPORT Q_DECL_IMPORT
#endif

#endif // QTSHERPAONNX_GLOBAL_H
