#ifndef QTSHERPAONNX_GLOBAL_H
#define QTSHERPAONNX_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(QTSHERPAONNX_LIBRARY)
#define QT6_SHERPA_ONNX_EXPORT Q_DECL_EXPORT
#else
#define QT6_SHERPA_ONNX_EXPORT Q_DECL_IMPORT
#endif

#endif // QTSHERPAONNX_GLOBAL_H
