#ifndef LIBQT6SHERPAONNX_GLOBAL_H
#define LIBQT6SHERPAONNX_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(LIBQT6SHERPAONNX_LIBRARY)
#define LIBQT6SHERPAONNX_EXPORT Q_DECL_EXPORT
#else
#define LIBQT6SHERPAONNX_EXPORT Q_DECL_IMPORT
#endif

#endif // LIBQT6SHERPAONNX_GLOBAL_H
